-- New predictions found in repo sweep + 3 additional deposited preregs to add to inventory
INSERT INTO tbltasks (name, description, priority, dateadded, startdate, duedate, addedfrom, status, rel_id, rel_type) VALUES
('Predict Euclid isotropy bound from hubble-anisotropy dipole', 'Repo /scratch/repos/hubble-anisotropy: H_0 dipole at RA=87.80, Dec=-47.19; scale center RA=301.41, Dec=-19.95. Euclid SHE+SIR/SPE will measure isotropy at sub-percent. Pre-register prediction: dipole magnitude SHOULD survive Euclid bound at |a_spin| < 10^-3 OR is falsified. Map dipole onto a_spin parameter in M_1 model.', 3, NOW(), CURDATE(), '2026-05-22', 1, 1, 25, 'project'),
('Predict Euclid H_0 from hubble-bubble reproducibility', 'Repo /scratch/repos/hubble-bubble (DOI 10.5281/zenodo.17388283): H_0 = 68.518 +/- 1.292 km/s/Mpc, 0.966 sigma concordance with Planck. If Euclid DR1 LE3 yields H_0 in this band, supports concordance. Pre-register the test before DR1.', 3, NOW(), CURDATE(), '2026-05-22', 1, 1, 25, 'project'),
('Pantheon-Omega_m-H_0 sensitivity prediction for Euclid', 'Repo /scratch/repos/pantheon-h0-omega-sensitivity (MNRAS MN-26-0837-L submission): Delta H_0 = -0.22 km/s/Mpc from Omega_m sensitivity. Euclid LE3 cross-survey Omega_m will sharpen this. Pre-register the predicted Delta H_0 magnitude vs Euclid Omega_m measurement.', 3, NOW(), CURDATE(), '2026-05-22', 1, 1, 25, 'project'),
('Cosmo-sterile-audit pipeline applied to Euclid DR1', 'Repo /scratch/repos/cosmo-sterile-audit (DOI 10.5281/zenodo.17482416): sterile analysis pipeline with hash-verified data, provenance manifests. Apply pipeline to Euclid DR1 ingest to validate data hygiene. Pre-register the pipeline application before DR1.', 2, NOW(), CURDATE(), '2026-05-29', 1, 1, 25, 'project'),
('UHA-pipeline xi_invariant.py applied to Euclid PHZ products', 'Repo /scratch/repos/uha-pipeline: xi_invariant computation. Apply to Euclid PHZ photometric-redshift products to validate xi-normalization across Euclid scale range. Pre-register threshold for xi-invariance.', 2, NOW(), CURDATE(), '2026-06-01', 1, 1, 25, 'project'),
('AUDIT UPDATE: Add 5 more Zenodo DOIs to inventory', 'Found in repo sweep 2026-05-01: hubble-bubble DOI 10.5281/zenodo.17388283 (H_0 reproducibility), cosmo-sterile-audit DOI 10.5281/zenodo.17482416 (sterile pipeline), nu-algebra DOI 10.5281/zenodo.17283314 (substrate). Plus from external IID audit: Euclid v2 DOI 10.5281/zenodo.19800601, A6 Implicitness DOI 10.5281/zenodo.19706285, Shell Geometry DOI 10.5281/zenodo.19322304. Update Z4_euclid_coverage_audit_2026-05-01.md to include these 6 deposits.', 3, NOW(), CURDATE(), '2026-05-08', 1, 1, 25, 'project'),
('Sweep low-relevance repos for hidden cosmology content', 'Quick grep over: aasb, aiwared, autonomoustheory, basin-theory, ebios, gfm, invariants, lenr-ncf, ncf, ncf-research, neutron-lifetime-paper, ommp, theories, untheory, un-algebra/un-algebra-paper, unkint-intelligence. Confirm NONE have prereggable Euclid claims. Report any hits as new tasks.', 1, NOW(), '2026-05-22', '2026-06-05', 1, 1, 25, 'project'),
('Forward-propagate IID rename in deposits and SAID', 'Per feedback_intellid_naming.md: replace AI with IID in (a) Z-track preregistration AI-disclosure sections at next deposit; (b) SAID framework templates; (c) eaiou platform field labels (alias ai_disclosure_level to iid_disclosure_level); (d) outgoing email Claude Code edit protocol. Eric: i hate ai word so much.', 2, NOW(), CURDATE(), '2026-05-15', 1, 1, 25, 'project');

SELECT COUNT(*) AS total_tasks FROM tbltasks WHERE rel_id = 25 AND rel_type = 'project';
